# Generated by Django 2.1 on 2018-08-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NO_NAME', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('name', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('view', models.CharField(max_length=128)),
                ('action', models.PositiveSmallIntegerField(choices=[(0, 'retrieve'), (1, 'list'), (2, 'create'), (3, 'update'), (4, 'partial_update'), (5, 'destroy')])),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='permissions',
            field=models.ManyToManyField(related_name='groups', to='view_user_permission.Permission'),
        ),
    ]
