# Generated by Django 2.1 on 2018-08-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_user_permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, 'retrieve'), (1, 'list'), (2, 'create'), (3, 'update'), (4, 'partial_update'), (5, 'destroy')]),
        ),
    ]
