# Generated by Django 2.1 on 2018-08-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_user_permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('retrieve', 'GET'), ('create', 'POST'), ('update', 'PUT'), ('partial_update', 'PATCH'), ('destroy', 'DELETE')], max_length=16),
        ),
    ]
